### PR TITLE
Keep it build script simple and clean

### PR DESCRIPTION
**Pull request by ClausKlein**
Use always cmake to build and install.
autopep8 *.py files.
Prevent use of debug suffix under Windows.

### CODE REVIEW

**Comment by lasote** [comment]
Honestly I'm afraid of changing this to CMake for all platforms, even the README is not mentioning CMake as a way to build it:

> To compile all files and run the test program, follow the instructions given at
the top of Makefile.in.  In short "./configure; make test", and if that goes
well, "make install" should work for most flavors of Unix.  For Windows, use
one of the special makefiles in win32/ or contrib/vstudio/ .  For VMS, use
make_vms.com.

That's why we kept the configure/make when possible.

**Comment by ClausKlein** [comment]
**Ok, but please fix this bug yourself:**
https://github.com/bincrafters/community/issues/210#issuecomment-378790446

**Comment by ClausKlein** [comment]
my future version builds under cygwin
------------------------------------------

klein_cl@WD002402 /cygdrive/c/msys64/home/klein_cl/.conan/data/zlib/1.2.11/bincrafters/testing/build/469b1a54bc41e97f540549f80591b5455bf6201c/zlib-1.2.11/_build
$ ninja -j 1 -v
ninja: warning: multiple rules generate libz.a. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
[1/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/adler32.o -MF CMakeFiles/zlibstatic.dir/adler32.o.d -o CMakeFiles/zlibstatic.dir/adler32.o   -c ../adler32.c
[2/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/compress.o -MF CMakeFiles/zlibstatic.dir/compress.o.d -o CMakeFiles/zlibstatic.dir/compress.o   -c ../compress.c
[3/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/crc32.o -MF CMakeFiles/zlibstatic.dir/crc32.o.d -o CMakeFiles/zlibstatic.dir/crc32.o   -c ../crc32.c
[4/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/deflate.o -MF CMakeFiles/zlibstatic.dir/deflate.o.d -o CMakeFiles/zlibstatic.dir/deflate.o   -c ../deflate.c
[5/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/gzclose.o -MF CMakeFiles/zlibstatic.dir/gzclose.o.d -o CMakeFiles/zlibstatic.dir/gzclose.o   -c ../gzclose.c
[6/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/gzlib.o -MF CMakeFiles/zlibstatic.dir/gzlib.o.d -o CMakeFiles/zlibstatic.dir/gzlib.o   -c ../gzlib.c
[7/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/gzread.o -MF CMakeFiles/zlibstatic.dir/gzread.o.d -o CMakeFiles/zlibstatic.dir/gzread.o   -c ../gzread.c
[8/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/gzwrite.o -MF CMakeFiles/zlibstatic.dir/gzwrite.o.d -o CMakeFiles/zlibstatic.dir/gzwrite.o   -c ../gzwrite.c
[9/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/inflate.o -MF CMakeFiles/zlibstatic.dir/inflate.o.d -o CMakeFiles/zlibstatic.dir/inflate.o   -c ../inflate.c
[10/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/infback.o -MF CMakeFiles/zlibstatic.dir/infback.o.d -o CMakeFiles/zlibstatic.dir/infback.o   -c ../infback.c
[11/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/inftrees.o -MF CMakeFiles/zlibstatic.dir/inftrees.o.d -o CMakeFiles/zlibstatic.dir/inftrees.o   -c ../inftrees.c
[12/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/inffast.o -MF CMakeFiles/zlibstatic.dir/inffast.o.d -o CMakeFiles/zlibstatic.dir/inffast.o   -c ../inffast.c
[13/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/trees.o -MF CMakeFiles/zlibstatic.dir/trees.o.d -o CMakeFiles/zlibstatic.dir/trees.o   -c ../trees.c
[14/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/uncompr.o -MF CMakeFiles/zlibstatic.dir/uncompr.o.d -o CMakeFiles/zlibstatic.dir/uncompr.o   -c ../uncompr.c
[15/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/zutil.o -MF CMakeFiles/zlibstatic.dir/zutil.o.d -o CMakeFiles/zlibstatic.dir/zutil.o   -c ../zutil.c
[16/20] : && /usr/bin/cmake.exe -E remove libz.a && /usr/bin/ar.exe qc libz.a  CMakeFiles/zlibstatic.dir/adler32.o CMakeFiles/zlibstatic.dir/compress.o CMakeFiles/zlibstatic.dir/crc32.o CMakeFiles/zlibstatic.dir/deflate.o CMakeFiles/zlibstatic.dir/gzclose.o CMakeFiles/zlibstatic.dir/gzlib.o CMakeFiles/zlibstatic.dir/gzread.o CMakeFiles/zlibstatic.dir/gzwrite.o CMakeFiles/zlibstatic.dir/inflate.o CMakeFiles/zlibstatic.dir/infback.o CMakeFiles/zlibstatic.dir/inftrees.o CMakeFiles/zlibstatic.dir/inffast.o CMakeFiles/zlibstatic.dir/trees.o CMakeFiles/zlibstatic.dir/uncompr.o CMakeFiles/zlibstatic.dir/zutil.o && /usr/bin/ranlib.exe libz.a && :
[17/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/example.dir/test/example.o -MF CMakeFiles/example.dir/test/example.o.d -o CMakeFiles/example.dir/test/example.o   -c ../test/example.c
[18/20] : && /usr/bin/cc    -Wl,--enable-auto-import CMakeFiles/example.dir/test/example.o  -o example.exe -Wl,--out-implib,libexample.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libz.a && :
[19/20] /usr/bin/cc   -I. -I../  -MD -MT CMakeFiles/minigzip.dir/test/minigzip.o -MF CMakeFiles/minigzip.dir/test/minigzip.o.d -o CMakeFiles/minigzip.dir/test/minigzip.o   -c ../test/minigzip.c
[20/20] : && /usr/bin/cc    -Wl,--enable-auto-import CMakeFiles/minigzip.dir/test/minigzip.o  -o minigzip.exe -Wl,--out-implib,libminigzip.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libz.a && :

**Comment by ClausKlein** [comment]
... and under MSYS
=============

klein_cl@WD002402 MSYS ~/.conan/data/zlib/1.2.11/bincrafters/testing/build/469b1a54bc41e97f540549f80591b5455bf6201c/zlib-1.2.11/_build
$ ninja -j1 -v
ninja: warning: multiple rules generate libz.a. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: bad deps log signature or version; starting over
[1/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/trees.o -MF CMakeFiles/zlibstatic.dir/trees.o.d -o CMakeFiles/zlibstatic.dir/trees.o   -c ../trees.c
[2/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/uncompr.o -MF CMakeFiles/zlibstatic.dir/uncompr.o.d -o CMakeFiles/zlibstatic.dir/uncompr.o   -c ../uncompr.c
[3/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/zutil.o -MF CMakeFiles/zlibstatic.dir/zutil.o.d -o CMakeFiles/zlibstatic.dir/zutil.o   -c ../zutil.c
[4/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/example.dir/test/example.o -MF CMakeFiles/example.dir/test/example.o.d -o CMakeFiles/example.dir/test/example.o   -c ../test/example.c
[5/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/minigzip.dir/test/minigzip.o -MF CMakeFiles/minigzip.dir/test/minigzip.o.d -o CMakeFiles/minigzip.dir/test/minigzip.o   -c ../test/minigzip.c
[6/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/inftrees.o -MF CMakeFiles/zlibstatic.dir/inftrees.o.d -o CMakeFiles/zlibstatic.dir/inftrees.o   -c ../inftrees.c
[7/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/inffast.o -MF CMakeFiles/zlibstatic.dir/inffast.o.d -o CMakeFiles/zlibstatic.dir/inffast.o   -c ../inffast.c
[8/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/adler32.o -MF CMakeFiles/zlibstatic.dir/adler32.o.d -o CMakeFiles/zlibstatic.dir/adler32.o   -c ../adler32.c
[9/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/compress.o -MF CMakeFiles/zlibstatic.dir/compress.o.d -o CMakeFiles/zlibstatic.dir/compress.o   -c ../compress.c
[10/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/crc32.o -MF CMakeFiles/zlibstatic.dir/crc32.o.d -o CMakeFiles/zlibstatic.dir/crc32.o   -c ../crc32.c
[11/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/deflate.o -MF CMakeFiles/zlibstatic.dir/deflate.o.d -o CMakeFiles/zlibstatic.dir/deflate.o   -c ../deflate.c
[12/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/gzclose.o -MF CMakeFiles/zlibstatic.dir/gzclose.o.d -o CMakeFiles/zlibstatic.dir/gzclose.o   -c ../gzclose.c
[13/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/gzlib.o -MF CMakeFiles/zlibstatic.dir/gzlib.o.d -o CMakeFiles/zlibstatic.dir/gzlib.o   -c ../gzlib.c
[14/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/gzread.o -MF CMakeFiles/zlibstatic.dir/gzread.o.d -o CMakeFiles/zlibstatic.dir/gzread.o   -c ../gzread.c
[15/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/gzwrite.o -MF CMakeFiles/zlibstatic.dir/gzwrite.o.d -o CMakeFiles/zlibstatic.dir/gzwrite.o   -c ../gzwrite.c
[16/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/inflate.o -MF CMakeFiles/zlibstatic.dir/inflate.o.d -o CMakeFiles/zlibstatic.dir/inflate.o   -c ../inflate.c
[17/20] /usr/bin/cc.exe  -I. -I../  -MD -MT CMakeFiles/zlibstatic.dir/infback.o -MF CMakeFiles/zlibstatic.dir/infback.o.d -o CMakeFiles/zlibstatic.dir/infback.o   -c ../infback.c
[18/20] : && /usr/bin/cmake.exe -E remove libz.a && /usr/bin/ar.exe qc libz.a  CMakeFiles/zlibstatic.dir/adler32.o CMakeFiles/zlibstatic.dir/compress.o CMakeFiles/zlibstatic.dir/crc32.o CMakeFiles/zlibstatic.dir/deflate.o CMakeFiles/zlibstatic.dir/gzclose.o CMakeFiles/zlibstatic.dir/gzlib.o CMakeFiles/zlibstatic.dir/gzread.o CMakeFiles/zlibstatic.dir/gzwrite.o CMakeFiles/zlibstatic.dir/inflate.o CMakeFiles/zlibstatic.dir/infback.o CMakeFiles/zlibstatic.dir/inftrees.o CMakeFiles/zlibstatic.dir/inffast.o CMakeFiles/zlibstatic.dir/trees.o CMakeFiles/zlibstatic.dir/uncompr.o CMakeFiles/zlibstatic.dir/zutil.o && /usr/bin/ranlib.exe libz.a && :
[19/20] : && /usr/bin/cc.exe   -Wl,--enable-auto-import CMakeFiles/minigzip.dir/test/minigzip.o  -o minigzip.exe -Wl,--out-implib,libminigzip.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libz.a && :
[20/20] : && /usr/bin/cc.exe   -Wl,--enable-auto-import CMakeFiles/example.dir/test/example.o  -o example.exe -Wl,--out-implib,libexample.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libz.a && :

**Comment by ClausKlein** [comment]
**My patch needs some love, ...**
 78%] Linking C static library ..\lib\libzlibstatic.a
[ 80%] Linking C static library ..\lib\libzlib.a
_There should only one static lib at atime._

I will fix it.

**Comment by SSE4** [comment]
@ClausKlein for now, we have decided not to switch all builds for CMake, at least for the current version, to avoid breakage. we may switch for the next zlib release, for sure, I believe. right now it builds fine under MSYS, so I am closing an issue.

**Pull request closed without merging**
