### PR TITLE
fix: only use autotools when building for Linux

### PR DESCRIPTION
**Pull request by theodelrieu**
Fixes iOS builds

### CODE REVIEW

**Comment by SSE4** [comment]
that seems to conflict with https://github.com/conan-community/conan-zlib/pull/76 by @tanshihaj 
what's the error message if build for iOS?

**Comment by SSE4** [comment]
also, @tanshihaj , if you can copy your error message in case of CMake, would be nice

**Comment by theodelrieu** [comment]
Will open a new PR

**Comment by tanshihaj** [comment]
well, actually there is no error building zlib with CMake. However building for iOS/watchOS/tvOS with CMake not so easy and I'm prefer to use autotools in this case. If someone face with problems building settings.os == macOS, settings.os_host == macOS configuration using CMake I think we can change https://github.com/conan-community/conan-zlib/blob/43cc886f9e4546e51941cfc0de08033da49d3cd7/conanfile.py#L48 like that:

`return self.settings.os == "Linux" or self.settings.os in ("iOS", "watchOS", "tvOS")`

But as I understand https://github.com/conan-community/community/issues/137 is connected with config settings.os == **Android**, settings.os_host == macOS so current version should be ok.

**Pull request closed without merging**
