### PR TITLE
check zlib conan package availability and viability in test_package

### PR DESCRIPTION
**Pull request by andy-held**
enough.c does not include zlib.h nor use anything from the library.

Instead a simple test can be used to assert correct package creation.

### CODE REVIEW

**Comment by lasote** [comment]
Hi! this is very very "interesting", I don't know how the `enough.c` ended there without a single include to zlib.
Nevertheless I think the example should call some funcion from the library, otherwise if we only use a variable of the .h we are not sure it is really linking correctly. Could you add a call to a zlib function?

**Comment by andy-held** [comment]
Good point.
Called zlibVersion instead.

**Comment by lasote** [comment]
Many thanks!!!!!!

**Comment by andy-held** [comment]
Thank you for maintaining!

**Pull request merged**
